### ISSUE TITLE
test.py和visualize_result.py可视化出错

### ISSUE THREAD

**Issue by yunqilingzhen** [megvii-research/PETR#21]
按照readme下的提示，训练完模型后，我用python3 tools/test.py $config $ckpt --show --show-dir $showdir 命令时报错：
请问这个是什么原因？
 Traceback (most recent call last):
  File "tools/test.py", line 258, in <module>
    main()
  File "tools/test.py", line 225, in main
    outputs = single_gpu_test(model, data_loader, args.show, args.show_dir)
  File "/disk5/shc/mmdetection3d/mmdet3d/apis/test.py", line 47, in single_gpu_test
    model.module.show_results(data, result, out_dir=out_dir)
  File "/disk5/shc/mmdetection3d/mmdet3d/models/detectors/mvx_two_stage.py", line 466, in show_results
    if isinstance(data['points'][0], DC):
KeyError: 'points'

另外使用visualize_results.py时也遇到了问题
Traceback (most recent call last):
  File "tools/misc/visualize_results.py", line 88, in <module>
    main()
  File "tools/misc/visualize_results.py", line 78, in main
    dataset.show(results, args.show_dir, pipeline=eval_pipeline)
  File "/disk5/shc/mmdetection3d/mmdet3d/datasets/nuscenes_dataset.py", line 567, in show
    show_result(points, show_gt_bboxes, show_pred_bboxes, out_dir,
  File "/disk5/shc/mmdetection3d/mmdet3d/core/visualizer/show_result.py", line 99, in show_result
    vis = Visualizer(points)
  File "/disk5/shc/mmdetection3d/mmdet3d/core/visualizer/open3d_vis.py", line 379, in __init__
    self.pcd, self.points_colors = _draw_points(
  File "/disk5/shc/mmdetection3d/mmdet3d/core/visualizer/open3d_vis.py", line 35, in _draw_points
    vis.get_render_option().point_size = points_size  # set points size
AttributeError: 'NoneType' object has no attribute 'point_size'

**Comment by yingfei1016** [comment]
Hello,
You can visualize the result refer to https://github.com/megvii-research/PETR#visualize

**Comment by zbaishancha** [comment]
你好，请问您是在本地远程连接服务器跑的代码吗？我也遇到了相同的问题，搜了一下，大概是因为本地没有显示器的原因

**Comment by yunqilingzhen** [comment]
> 你好，请问您是在本地远程连接服务器跑的代码吗？我也遇到了相同的问题，搜了一下，大概是因为本地没有显示器的原因

你好，作者已经在上面恢复了可视化方法
