### ISSUE TITLE
关于dataset路径报错

### ISSUE THREAD

**Issue by BestBUCKY** [megvii-research/PETR#54]
您好，我在复现petrv2_seg的时候，将cfg中的data_root修改为正确的路径“./data/Dataset/nuScenses",但是在执行的时候仍然出现了路径错误
2022-09-21 10:42:53,544 - mmdet - INFO - workflow: [('train', 1)], max: 24 epochs
2022-09-21 10:42:53,546 - mmdet - INFO - Checkpoints will be saved to /media/djy/H/PETR/work_dirs/petrv2 by HardDiskBackend.
Traceback (most recent call last):
  File "tools/train.py", line 258, in <module>
    main()
  File "tools/train.py", line 247, in main
    train_model(
  File "/home/djy/mmdetection3d/mmdet3d/apis/train.py", line 28, in train_model
    train_detector(
  File "/home/djy/mmdetection/mmdet/apis/train.py", line 244, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/djy/anaconda3/envs/petr/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/djy/anaconda3/envs/petr/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/home/djy/anaconda3/envs/petr/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/djy/anaconda3/envs/petr/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/home/djy/anaconda3/envs/petr/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/home/djy/anaconda3/envs/petr/lib/python3.8/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/djy/anaconda3/envs/petr/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/djy/anaconda3/envs/petr/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/djy/anaconda3/envs/petr/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/djy/mmdetection3d/mmdet3d/datasets/custom_3d.py", line 357, in __getitem__
    data = self.prepare_train_data(idx)
  File "/home/djy/mmdetection3d/mmdet3d/datasets/custom_3d.py", line 154, in prepare_train_data
    example = self.pipeline(input_dict)
  File "/home/djy/mmdetection/mmdet/datasets/pipelines/compose.py", line 41, in __call__
    data = t(data)
  File "/home/djy/mmdetection3d/mmdet3d/datasets/pipelines/loading.py", line 47, in __call__
    [mmcv.imread(name, self.color_type) for name in filename], axis=-1)
  File "/home/djy/mmdetection3d/mmdet3d/datasets/pipelines/loading.py", line 47, in <listcomp>
    [mmcv.imread(name, self.color_type) for name in filename], axis=-1)
  File "/home/djy/anaconda3/envs/petr/lib/python3.8/site-packages/mmcv/image/io.py", line 176, in imread
    check_file_exist(img_or_path,
  File "/home/djy/anaconda3/envs/petr/lib/python3.8/site-packages/mmcv/utils/path.py", line 23, in check_file_exist
    raise FileNotFoundError(msg_tmpl.format(filename))
FileNotFoundError: img file does not exist: /data/Dataset/nuScenes/samples/CAM_FRONT/n015-2018-08-03-15-00-36+0800__CAM_FRONT__1533279682112460.jpg

Killing subprocess 28739
Traceback (most recent call last):
  File "/home/djy/anaconda3/envs/petr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/djy/anaconda3/envs/petr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/djy/anaconda3/envs/petr/lib/python3.8/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/djy/anaconda3/envs/petr/lib/python3.8/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/djy/anaconda3/envs/petr/lib/python3.8/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/djy/anaconda3/envs/petr/bin/python3', '-u', 'tools/train.py', '--local_rank=0', 'projects/configs/petrv2/petrv2_BEVseg.py', '--launcher', 'pytorch', '--work-dir', 'work_dirs/petrv2/']' returned non-zero exit status 1.

看上去是使用了一个默认的路径，但是我没找到修改路径的代码在哪，请问有什么解决办法吗

**Comment by yingfei1016** [comment]
I think is the default path in our provided pkl file.
You can modify File "/home/djy/mmdetection3d/mmdet3d/datasets/pipelines/loading.py", line 47, in call
[mmcv.imread(name, self.color_type) for name in filename], axis=-1).

name.replace("/data/Dataset/nuScenes/", "./data/Dataset/nuScenses")

**Comment by BestBUCKY** [comment]
> I think is the default path in our provided pkl file. You can modify File "/home/djy/mmdetection3d/mmdet3d/datasets/pipelines/loading.py", line 47, in call [mmcv.imread(name, self.color_type) for name in filename], axis=-1).
> 
> name.replace("/data/Dataset/nuScenes/", "./data/Dataset/nuScenses")

thanks for your reply，it works

**Comment by forest-Hu** [comment]
thank you!  It help!
